mycelial/mycelial

console/components/Flow/index.tsx
Fixes the bug where publishing multiple times creates multiple pipes (mostly.. if you hit the button really fast I think it's technically still possible, but I didn't come across this situation in manual testing).
=> split up api calls so updating the ids is easier

myceliald/src/runtime.rs, pipe/runtime/src/command_channel/tokio.rs, pipe/runtime/src/config.rs, pipe/runtime/src/pipe.rs, pipe/runtime/src/registry.rs, pipe/runtime/src/scheduler.rs, pipe/runtime/src/sections/hello_world/destination.rs, pipe/runtime/src/sections/hello_world/source.rs, pipe/runtime/src/sections/mycelial_server/destination.rs, pipe/runtime/src/sections/mycelial_server/source.rs, pipe/runtime/src/sections/sqlite_connector/destination.rs, pipe/runtime/src/sections/sqlite_connector/source.rs, pipe/runtime/src/sections/sqlite_physical_replication/destination.rs, pipe/runtime/src/sections/sqlite_physical_replication/source.rs, pipe/runtime/src/storage.rs, pipe/runtime/src/types.rs, pipe/section/section_impls/sqlite_connector/src/source.rs, pipe/section/section_impls/sqlite_connector/tests/source.rs, pipe/section/section_impls/stub/src/lib.rs, pipe/section/src/command_channel.rs, pipe/section/src/dummy/command_channel.rs
- Reworks how section traits are propagated
- Adds ability to stream sqlite only once
=> Section channel traits rework

docs/Tutorial.md
Fixed incorrect link and verify others.
=> fix incorrect link

pipe/section/section_impls/kafka/src/destination.rs
* don't send message downstream 
* ack the msg
=> Ack messages in Kafka Dest

pipe/runtime/src/scheduler.rs
- Fixes scheduler deadlock on retrieving error from pipe when pipe was rescheduled
- Adds constant delay between for pipe rescheduling
=> Fix scheduler

Cargo.lock, console/components/nodes.tsx, myceliald/config.example.toml, myceliald/src/runtime.rs, pipe/runtime/Cargo.toml, pipe/runtime/src/sections/mod.rs, pipe/runtime/src/sections/snowflake/destination.rs, pipe/runtime/src/sections/snowflake/mod.rs, pipe/runtime/src/sections/snowflake/source.rs
=> Snowflake sections

pipe/section/section_impls/postgres_connector/src/lib.rs
=> pg: change DOUBLE to DOUBLE PRECISION

Cargo.lock, pipe/section/section_impls/excel_connector/Cargo.toml, pipe/section/section_impls/excel_connector/src/source.rs
=> Excel source can watch multiple files at once.

.github/workflows/check.yml, pipe/section/section_impls/sqlite_connector/scripts/add_user.sh, pipe/section/section_impls/sqlite_connector/scripts/create_users_testdb.sh
It's a bit of a pain to have to include mycelite every time you have to do something to the db for testing. These scripts take care of that for you. The assumption is that mycelite is set up as specified in the tutorial.
=> Scripts to create the db and add users

Cargo.lock, Cargo.toml, common/src/lib.rs, console/components/Flow/index.tsx, console/components/nodes.tsx, myceliald/Cargo.toml, myceliald/Makefile, myceliald/config.example.toml, myceliald/src/constructors/file.rs, myceliald/src/constructors/mod.rs, myceliald/src/runtime.rs, pipe/section/section_impls/file/Cargo.toml, pipe/section/section_impls/file/src/destination.rs, pipe/section/section_impls/file/src/lib.rs, pipe/section/section_impls/file/src/source.rs, pipe/section/section_impls/mycelial_server/Cargo.toml, pipe/section/section_impls/mycelial_server/src/destination.rs, pipe/section/src/message.rs
Adds simple file source/destination sections
=> Add file section

console/src/actions/clients.ts, console/src/actions/pipes.ts, console/src/actions/workspaceDataLoader.ts, console/src/components/DataNode/index.tsx, console/src/components/Flow/index.tsx, console/src/stores/flowStore.tsx, console/src/utils/constants.ts, console/src/utils/index.ts
Adds ability to have transforms in the UI. 
Changes include:
* We no longer combine sections that are part of different workflows/pipes just because they look the same (except for mycelial_server sources and destinations, which are combined for convenience because conceptually they're linked).
* We no longer allow a source/destination to be connected to multiple destinations/sources. This means all workflows/pipes will be represented as a straight line, which is closer to what they are on the backend, which is a series of sections.
=> [GEN-1004] Add transforms to UI

console/src/app.tsx, server/Makefile, server/src/main.rs
here's the env file for the server
```.env
export AUTH0_AUTHORITY=<insert value here> # same as VITE_AUTH0_DOMAIN
export AUTH0_AUDIENCE=<insert value here> # same as VITE_AUTH0_AUDIENCE
```
and the one for the frontend
```.env
VITE_USE_AUTH0=true
VITE_AUTH0_DOMAIN=<insert value here> # same as AUTH0_AUTHORITY
VITE_AUTH0_CLIENT_ID=<insert value here>
VITE_AUTH0_AUDIENCE=<insert value here> # same as AUTH0_AUDIENCE
```
=> use env vars more and use those to get jwks

Cargo.lock, common/src/lib.rs, console/package-lock.json, console/src/types.ts, console/src/utils/constants.ts, myceliald/Cargo.toml, myceliald/config.example.toml, myceliald/src/constructors/sqlite_connector.rs, myceliald/src/main.rs, pipe/section/section_impls/sqlite_connector/Cargo.toml, pipe/section/section_impls/sqlite_connector/src/destination.rs, pipe/section/section_impls/sqlite_connector/src/lib.rs, pipe/section/section_impls/sqlite_connector/src/source.rs, pipe/section/section_impls/sqlite_connector/tests/source.rs
- replaces 'append only' behavior on sqlite connector source side with user-provided query
- adds ability to truncate destination
=> Query based sqlite connector

console/src/components/Instructions.tsx, console/src/components/Workspaces.tsx
=> add instructions box to frontend

server/src/app.rs, server/src/daemon_auth.rs, server/src/daemon_basic_auth.rs, server/src/ingestion.rs, server/src/main.rs, server/src/pipe.rs, server/src/workspace.rs
Pulls the controllers and the App out of the server's main. I did this as part of understanding how our auth works.
=> Extract controllers and App from server

server/src/main.rs
=> Add default database url value

pipe/section/section_impls/exec/src/lib.rs
Avoid sending message downstream if acks are not pass-through.
=> Temporary fix for exec section

Cargo.lock, pipe/runtime/Cargo.toml, pipe/runtime/src/pipe.rs, pipe/runtime/src/scheduler.rs, pipe/runtime/tests/scheduler.rs, pipe/section/section_impls/stub/Cargo.toml, pipe/section/section_impls/stub/src/lib.rs
- Update stub section to consume whole input
- Auto-inject stub section to the end of each pipe
- Switch from log to tracing
=> Update stub section and pipe building process

pipe/section/section_impls/sqlite_connector/src/source.rs, pipe/section/section_impls/sqlite_connector/tests/source.rs
=> Map NULL type properly

myceliald/src/constructors/typecast_transformer.rs, pipe/runtime/src/scheduler.rs, pipe/section/section_impls/typecast_transformer/src/lib.rs, pipe/section/src/message.rs
- Allow `*` to specify all columns
- Update casting implementation, move it to `ValueView` from `Value`
=> Update typecast transformer

pipe/section/section_impls/postgres_connector/src/destination.rs, pipe/section/section_impls/postgres_connector/src/lib.rs
- PG destination performs inserts in batches
- DataFrame columns are used to specify the fields to insert into the table
=> Update postgres destination

Cargo.lock, myceliald/src/constructors/postgres_connector.rs, myceliald/src/lib.rs, pipe/section/section_impls/csv_transform/examples/to_csv.rs, pipe/section/section_impls/postgres_connector/Cargo.toml, pipe/section/section_impls/postgres_connector/examples/basic.rs, pipe/section/section_impls/postgres_connector/src/lib.rs, pipe/section/section_impls/postgres_connector/src/source.rs, pipe/section/section_impls/postgres_connector/src/stateful_query.rs
Add experimental support for stateful queries
=> Update postgres source

Cargo.lock, Cargo.toml, common/src/lib.rs, console/src/actions/clients.ts, myceliald/Cargo.toml, myceliald/config.example.toml, myceliald/src/constructors/inspect.rs, myceliald/src/constructors/mod.rs, myceliald/src/constructors/typecast_transformer.rs, myceliald/src/runtime.rs, pipe/section/section_impls/inspect/Cargo.toml, pipe/section/section_impls/inspect/src/lib.rs, pipe/section/section_impls/s3/src/source.rs, pipe/section/src/lib.rs, pipe/section/src/message.rs, pipe/section/src/pretty_print.rs
Inspect section prints contents of message, which can useful for data inspection/debug.
=> Add inspect section
